/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./components/common/BaseIcon.vue')['default']
    BaseMovieSwiper: typeof import('./components/common/BaseMovieSwiper.vue')['default']
    BookingAction: typeof import('./components/features/client/booking/BookingAction.vue')['default']
    BookingConfirmModal: typeof import('./components/features/client/booking/BookingTicket.vue')['default']
    BookingCountdownTimer: typeof import('./components/features/client/booking/BookingCountdownTimer.vue')['default']
    BookingFood: typeof import('./components/features/client/booking/BookingFood.vue')['default']
    BookingInfo: typeof import('./components/features/client/booking/BookingInfo.vue')['default']
    BookingPayment: typeof import('./components/features/client/booking/BookingPayment.vue')['default']
    BookingSeat: typeof import('./components/features/client/booking/BookingSeat.vue')['default']
    BookingTicket: typeof import('./components/features/client/booking/BookingTicket.vue')['default']
    ClientFooter: typeof import('./components/layout/client/ClientFooter.vue')['default']
    ClientNavbar: typeof import('./components/layout/client/ClientNavbar.vue')['default']
    HomeBanner: typeof import('./components/features/client/home/HomeBanner.vue')['default']
    HomeBlog: typeof import('./components/features/client/home/HomeBlog.vue')['default']
    HomeNews: typeof import('./components/features/client/home/HomeNews.vue')['default']
    HomeShowing: typeof import('./components/features/client/home/HomeShowing.vue')['default']
    HomeUpcoming: typeof import('./components/features/client/home/HomeUpcoming.vue')['default']
    LoginModal: typeof import('./components/layout/modal/LoginModal.vue')['default']
    MovieDetail: typeof import('./components/features/client/movie/MovieDetail.vue')['default']
    MovieTicket: typeof import('./components/features/client/movie/MovieTicket.vue')['default']
    RegisterModal: typeof import('./components/layout/modal/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
